start:
  - '๐ ะะพะฑัะพ ะฟะพะถะฐะปะพะฒะฐัั ะฒ ะฝะฐั ะฑะพั'
  - ''
  - '๐๏ธ ะะดะตัั ัั ะผะพะถะตัั ะทะฐะบะฐะทะฐัั ะฟะปะฐะณะธะฝ ะดะปั Minecraft ะฟะพะด <b>ะปัะฑัั ะฒะตััะธั</b>'
  - '๐ฆ ะะปะธ ะฒัะฑัะฐัั ะธะท ัะถะต ะณะพัะพะฒัั ัะตัะตะฝะธะน ะฒ ะผะฐะณะฐะทะธะฝะต'
  - ''
  - 'โ๏ธ ะัะต ะดะตะปะฐะตะผ ะฟะพ ัะฒะพะธะผ ะฟะพะถะตะปะฐะฝะธัะผ!'
  - '๐ฅ ะ ะดะฐ, ะฒัะต ะฟัะฐะฒะบะธ โ <b>ะฟะพะปะฝะพัััั ะฑะตัะฟะปะฐัะฝัะต</b>'
  - ''
  - '๐ฌ ะะธัะธ ะฟััะผะพ ัะตะนัะฐั โ ัะถะต ะฟัะตะดััะฐะฒะปัั ะบะฐะบ ะฟะธัั ัะฒะพะน ะฟะปะฐะณะธะฝ)'
keyboard:
  make_order: '๐ธ ะกะดะตะปะฐัั ะทะฐะบะฐะท'
  shop: '๐๏ธ ะะฐะณะฐะทะธะฝ'
  support: '๐ฌ ะะพะดะดะตัะถะบะฐ'
  my_orders: '๐ ะะพะธ ะทะฐะบะฐะทั'
shop:
  empty: 'ะขัั ัะบะพัะพ ััะพ-ัะพ ะฑัะดะตั...'
  entry:
    - '๐ฆ ะะปะฐะณะธะฝ {name}'
    - ''
    - '๐ ะะฟะธัะฐะฝะธะต:'
    - '{description}'
  message: '๐ฆ ะะฐัะธ ะณะพัะพะฒัะต ะฟะปะฐะณะธะฝั:'
  button: 'โญ {name}'
  buy_button: '๐ ะัะฟะธัั'
make_order:
  version: '๐ซณ ะัะฑะตัะธัะต ะฒะตััะธั ัะตัะฒะตัะฐ ะดะปั ะฟะปะฐะณะธะฝะฐ:'
  tech_task: 'โ๏ธ ะะฐะฟะธัะธัะต ะขะ (ะขะตัะฝะธัะตัะบะพะต ะทะฐะดะฐะฝะธะต):'
status:
  not_paid: 'ะะต ะพะฟะปะฐัะตะฝ'
  not_started: 'ะะต ะฝะฐัะฐั'
  in_process: 'ะ ะฟัะพัะตััะต'
  ready: 'ะะพัะพะฒ'
my_orders:
  empty: 'ะฃ ะฒะฐั ะฝะตัั ะทะฐะบะฐะทะพะฒ, ัะฐะผะพะต ะฒัะตะผั ัะดะตะปะฐัั ััะพ. ะ ะฟะพะบะฐ ะดะตัะถะธัะต ะฑะฐะฝะฐะฝ ัะพััะฒััะฒะธั ๐'
  button: 'ะะฐะบะฐะท #{id}'
order:
  message:
    - 'ะะฐะบะฐะท: #{id}'
    - 'ะกัะฐััั: {status}'
    - ''
    - 'ะขะตัะฝะธัะตัะบะพะต ะทะฐะดะฐะฝะธะต:'
    - '{task}'
  buttons:
    hurry_up: '๐ข ะะพัะพัะพะฟะธัั'
    support: '๐ ะะพะดะดะตัะถะบะฐ'
