start:
  - 'ü§ó –ü—Ä–∏–≤–µ—Ç—Å—Ç–≤—É—é –≤–∞—Å –≤ –Ω–∞—à–µ–º –±–æ—Ç–µ'
  - ''
  - '–ó–¥–µ—Å—å –≤—ã –º–æ–∂–µ—Ç–µ –∑–∞–∫–∞–∑–∞—Ç—å –ø–ª–∞–≥–∏–Ω'
  - '–ò–ª–∏ –∫—É–ø–∏—Ç—å —É–∂–µ –≥–æ—Ç–æ–≤—ã–π'
  - ''
  - '‚úÖ –ü—Ä–∞–≤–∫–∏ –ø–æ–ª–Ω–æ—Å—Ç—å—é –±–µ—Å–ø–ª–∞—Ç–Ω—ã–µ'
keyboard:
  make_order: 'üí∏ –°–¥–µ–ª–∞—Ç—å –∑–∞–∫–∞–∑'
  shop: 'üõí –ú–∞–≥–∞–∑–∏–Ω'
  support: 'üíÅ –ü–æ–¥–¥–µ—Ä–∂–∫–∞'
  my_orders: 'üìÑ –ú–æ–∏ –∑–∞–∫–∞–∑—ã'
shop:
  empty: '–¢—É—Ç —Å–∫–æ—Ä–æ —á—Ç–æ-—Ç–æ –±—É–¥–µ—Ç...'
  entry:
    - '‚≠ï –ü–ª–∞–≥–∏–Ω {name}'
    - ''
    - 'üî∞ –û–ø–∏—Å–∞–Ω–∏–µ:'
    - '{description}'
  button: 'üõí –ö—É–ø–∏—Ç—å'
make_order:
  version: 'ü´≥ –í—ã–±–µ—Ä–∏—Ç–µ –≤–µ—Ä—Å–∏—é —Å–µ—Ä–≤–µ—Ä–∞ –¥–ª—è –ø–ª–∞–≥–∏–Ω–∞:'
  tech_task: '‚úçÔ∏è –ù–∞–ø–∏—à–∏—Ç–µ –¢–ó (–¢–µ—Ö–Ω–∏—á–µ—Å–∫–æ–µ –∑–∞–¥–∞–Ω–∏–µ):'
status:
  not_paid: '–ù–µ –æ–ø–ª–∞—á–µ–Ω'
  not_started: '–ù–µ –Ω–∞—á–∞—Ç'
  in_process: '–í –ø—Ä–æ—Ü–µ—Å—Å–µ'
  ready: '–ì–æ—Ç–æ–≤'
my_orders:
  empty: '–£ –≤–∞—Å –Ω–µ—Ç—É –∑–∞–∫–∞–∑–æ–≤, —Å–∞–º–æ–µ –≤—Ä–µ–º—è —Å–¥–µ–ª–∞—Ç—å —ç—Ç–æ. –ê –ø–æ–∫–∞ –¥–µ—Ä–∂–∏—Ç–µ –±–∞–Ω–∞–Ω —Å–æ—á—É–≤—Å—Ç–≤–∏—è üçå'
  button: '–ó–∞–∫–∞–∑ #{id}'
order:
  message:
    - '–ó–∞–∫–∞–∑: #{id}'
    - '–°—Ç–∞—Ç—É—Å: {status}'
    - ''
    - '–¢–µ—Ö–Ω–∏—á–µ—Å–∫–æ–µ –∑–∞–¥–∞–Ω–∏–µ:'
    - '{task}'
  buttons:
    hurry_up: 'üì¢ –ü–æ—Ç–æ—Ä–æ–ø–∏—Ç—å'
    support: 'üíÅ –ü–æ–¥–¥–µ—Ä–∂–∫–∞'
