start:
  - '๐ ะะพะฑัะพ ะฟะพะถะฐะปะพะฒะฐัั ะฒ ะฝะฐั ะฑะพั'
  - ''
  - '๐๏ธ ะะดะตัั ัั ะผะพะถะตัั ะทะฐะบะฐะทะฐัั ะฟะปะฐะณะธะฝ ะดะปั Minecraft ะฟะพะด <b>ะปัะฑัั ะฒะตััะธั</b>'
  - '๐ฆ ะะปะธ ะฒัะฑัะฐัั ะธะท ัะถะต ะณะพัะพะฒัั ัะตัะตะฝะธะน ะฒ ะผะฐะณะฐะทะธะฝะต'
  - ''
  - 'โ๏ธ ะัะต ะดะตะปะฐะตะผ ะฟะพ ัะฒะพะธะผ ะฟะพะถะตะปะฐะฝะธัะผ!'
  - '๐ฅ ะ ะดะฐ, ะฒัะต ะฟัะฐะฒะบะธ โ <b>ะฟะพะปะฝะพัััั ะฑะตัะฟะปะฐัะฝัะต</b>'
  - ''
  - '๐ฌ ะะธัะธ ะฟััะผะพ ัะตะนัะฐั โ ัะถะต ะฟัะตะดััะฐะฒะปัั ะบะฐะบ ะฟะธัั ัะฒะพะน ะฟะปะฐะณะธะฝ)'
keyboard:
  make_order: '๐ธ ะกะดะตะปะฐัั ะทะฐะบะฐะท'
  shop: '๐๏ธ ะะฐะณะฐะทะธะฝ'
  support: '๐ฌ ะะพะดะดะตัะถะบะฐ'
  my_orders: '๐ ะะพะธ ะทะฐะบะฐะทั'
shop:
  empty: 'ะขัั ัะบะพัะพ ััะพ-ัะพ ะฑัะดะตั...'
  entry:
    - '๐ฆ ะะปะฐะณะธะฝ {name}'
    - ''
    - '๐ ะะฟะธัะฐะฝะธะต:'
    - '{description}'
  message: '๐ฆ ะะฐัะธ ะณะพัะพะฒัะต ะฟะปะฐะณะธะฝั:'
  button: 'โญ {name} โ {price}โฝ'
  buy_button: '๐ ะัะฟะธัั'
  not_found: 'โ ะะปะฐะณะธะฝ ะฝะต ะฝะฐะนะดะตะฝ'
  pay_button: '๐ณ ะะฟะปะฐัะธัั'
  payment_info:
    - '๐ฐ ะะฟะปะฐัะฐ ะฟะปะฐะณะธะฝะฐ {name}'
    - ''
    - '๐ต ะกัะผะผะฐ: {price} โฝ'
    - ''
    - 'ะะฐะถะผะธัะต ะบะฝะพะฟะบั ะฝะธะถะต ะดะปั ะพะฟะปะฐัั:'
  plugin_not_found_after_payment:
    - 'โ ะะฟะปะฐัะฐ ะฟัะพัะปะฐ ััะฟะตัะฝะพ'
    - 'โ ะะพ ะฟะปะฐะณะธะฝ ะฝะต ะฝะฐะนะดะตะฝ ะฒ ัะธััะตะผะต'
    - ''
    - 'ะะฑัะฐัะธัะตัั ะฒ ะฟะพะดะดะตัะถะบั ั ะฝะพะผะตัะพะผ ะพะฟะตัะฐัะธะธ: <b>{operation_id}</b>'
  success_payment:
    - 'โ ะะฟะปะฐัะฐ ะฟัะพัะปะฐ ััะฟะตัะฝะพ'
    - ''
    - '๐ ะั ะฟัะธะพะฑัะตะปะธ ะฟะปะฐะณะธะฝ: <b>{name}</b>'
    - '๐ ะะฐั ะฟะปะฐะณะธะฝ ะฒ ะฟัะพัะตััะต ะพัะฟัะฐะฒะบะธ'
  caption: '๐ {name}'
  file_not_found:
    - 'โ ะคะฐะนะป ะฟะปะฐะณะธะฝะฐ ะฝะต ะฝะฐะนะดะตะฝ ะฝะฐ ัะตัะฒะตัะต'
    - 'ะะฑัะฐัะธัะตัั ะฒ ัะตั ะฟะพะดะดะตัะถะบั ั ะฝะพะผะตัะพะผ ะพะฟะตัะฐัะธะธ: <b>{operation_id}</b>'
  payment_failed:
    - 'โ ะัะธะฑะบะฐ ะฟัะธ ะพะฟะปะฐัะต'
    - ''
    - 'ะะต ัะดะฐะปะพัั ะฟัะพะฒะตััะธ ะฟะปะฐััะถ'
    - '๐ณ ะะพะผะตั ะพะฟะตัะฐัะธะธ: <b>{operation_id}</b>'
make_order:
  version: '๐ซณ ะัะฑะตัะธัะต ะฒะตััะธั ัะตัะฒะตัะฐ ะดะปั ะฟะปะฐะณะธะฝะฐ:'
  tech_task: 'โ๏ธ ะะฐะฟะธัะธัะต ะขะ (ะขะตัะฝะธัะตัะบะพะต ะทะฐะดะฐะฝะธะต):'
status:
  not_paid: 'ะะต ะพะฟะปะฐัะตะฝ'
  not_started: 'ะะต ะฝะฐัะฐั'
  in_process: 'ะ ะฟัะพัะตััะต'
  ready: 'ะะพัะพะฒ'
my_orders:
  empty: 'ะฃ ะฒะฐั ะฝะตัั ะทะฐะบะฐะทะพะฒ, ัะฐะผะพะต ะฒัะตะผั ัะดะตะปะฐัั ััะพ. ะ ะฟะพะบะฐ ะดะตัะถะธัะต ะฑะฐะฝะฐะฝ ัะพััะฒััะฒะธั ๐'
  button: 'ะะฐะบะฐะท #{id}'
order:
  message:
    - 'ะะฐะบะฐะท: #{id}'
    - 'ะกัะฐััั: {status}'
    - ''
    - 'ะขะตัะฝะธัะตัะบะพะต ะทะฐะดะฐะฝะธะต:'
    - '{task}'
  buttons:
    hurry_up: '๐ข ะะพัะพัะพะฟะธัั'
    support: '๐ ะะพะดะดะตัะถะบะฐ'
admin:
  keyboard:
    shop: '๐๏ธ ะะฐัััะพะนะบะธ ะผะฐะณะฐะทะธะฝะฐ'
    orders: '๐ ะฃะฟัะฐะฒะปะตะฝะธะต ะทะฐะบะฐะทะฐะผะธ'
    back: '๐ ะะตัะฝััััั ะฒ ะผะตะฝั'
  shop:
    welcome: '๐ฆ ะะพั ะฒัะต ะฟะปะฐะณะธะฝั:'
  welcome: '๐๏ธ ะะพะฑัะพ ะฟะพะถะฐะปะพะฒะฐัั ะฒ ะฐะดะผะธะฝ ะฟะฐะฝะตะปั'
  wrong_password: 'โ ะะตะฒะตัะฝัะน ะฟะฐัะพะปั. ๐ ะััะฐะปะพัั <b>{attempts}</b> ะฟะพะฟััะบะธ'
  enter_password: '๐ ะะฒะตะดะธัะต ะฟะฐัะพะปั:'
  blocked: '๐ซ ะะพัััะฟ ะทะฐะฑะปะพะบะธัะพะฒะฐะฝ! ะัะตะฒััะตะฝะพ ะบะพะปะธัะตััะฒะพ ะฟะพะฟััะพะบ'
