start:
  - 'üéâ –î–æ–±—Ä–æ –ø–æ–∂–∞–ª–æ–≤–∞—Ç—å –≤ –Ω–∞—à –±–æ—Ç'
  - ''
  - 'üõ†Ô∏è –ó–¥–µ—Å—å —Ç—ã –º–æ–∂–µ—à—å –∑–∞–∫–∞–∑–∞—Ç—å –ø–ª–∞–≥–∏–Ω –¥–ª—è Minecraft –ø–æ–¥ <b>–ª—é–±—É—é –≤–µ—Ä—Å–∏—é</b>'
  - 'üì¶ –ò–ª–∏ –≤—ã–±—Ä–∞—Ç—å –∏–∑ —É–∂–µ –≥–æ—Ç–æ–≤—ã—Ö —Ä–µ—à–µ–Ω–∏–π –≤ –º–∞–≥–∞–∑–∏–Ω–µ'
  - ''
  - '‚öôÔ∏è –í—Å–µ –¥–µ–ª–∞–µ–º –ø–æ —Ç–≤–æ–∏–º –ø–æ–∂–µ–ª–∞–Ω–∏—è–º!'
  - 'üî• –ò –¥–∞, –≤—Å–µ –ø—Ä–∞–≤–∫–∏ ‚Äî <b>–ø–æ–ª–Ω–æ—Å—Ç—å—é –±–µ—Å–ø–ª–∞—Ç–Ω—ã–µ</b>'
  - ''
  - 'üí¨ –ü–∏—à–∏ –ø—Ä—è–º–æ —Å–µ–π—á–∞—Å ‚Äî —É–∂–µ –ø—Ä–µ–¥—Å—Ç–∞–≤–ª—è—é –∫–∞–∫ –ø–∏—à—É —Ç–≤–æ–π –ø–ª–∞–≥–∏–Ω)'
keyboard:
  make_order: 'üí∏ –°–¥–µ–ª–∞—Ç—å –∑–∞–∫–∞–∑'
  shop: 'üõçÔ∏è –ú–∞–≥–∞–∑–∏–Ω'
  support: 'üí¨ –ü–æ–¥–¥–µ—Ä–∂–∫–∞'
  my_orders: 'üìÑ –ú–æ–∏ –∑–∞–∫–∞–∑—ã'
shop:
  empty: '–¢—É—Ç —Å–∫–æ—Ä–æ —á—Ç–æ-—Ç–æ –±—É–¥–µ—Ç...'
  entry:
    - '‚≠ï –ü–ª–∞–≥–∏–Ω {name}'
    - ''
    - 'üî∞ –û–ø–∏—Å–∞–Ω–∏–µ:'
    - '{description}'
  button: '‚≠ï {name}'
  buy_button: 'üõí –ö—É–ø–∏—Ç—å'
make_order:
  version: 'ü´≥ –í—ã–±–µ—Ä–∏—Ç–µ –≤–µ—Ä—Å–∏—é —Å–µ—Ä–≤–µ—Ä–∞ –¥–ª—è –ø–ª–∞–≥–∏–Ω–∞:'
  tech_task: '‚úçÔ∏è –ù–∞–ø–∏—à–∏—Ç–µ –¢–ó (–¢–µ—Ö–Ω–∏—á–µ—Å–∫–æ–µ –∑–∞–¥–∞–Ω–∏–µ):'
status:
  not_paid: '–ù–µ –æ–ø–ª–∞—á–µ–Ω'
  not_started: '–ù–µ –Ω–∞—á–∞—Ç'
  in_process: '–í –ø—Ä–æ—Ü–µ—Å—Å–µ'
  ready: '–ì–æ—Ç–æ–≤'
my_orders:
  empty: '–£ –≤–∞—Å –Ω–µ—Ç—É –∑–∞–∫–∞–∑–æ–≤, —Å–∞–º–æ–µ –≤—Ä–µ–º—è —Å–¥–µ–ª–∞—Ç—å —ç—Ç–æ. –ê –ø–æ–∫–∞ –¥–µ—Ä–∂–∏—Ç–µ –±–∞–Ω–∞–Ω —Å–æ—á—É–≤—Å—Ç–≤–∏—è üçå'
  button: '–ó–∞–∫–∞–∑ #{id}'
order:
  message:
    - '–ó–∞–∫–∞–∑: #{id}'
    - '–°—Ç–∞—Ç—É—Å: {status}'
    - ''
    - '–¢–µ—Ö–Ω–∏—á–µ—Å–∫–æ–µ –∑–∞–¥–∞–Ω–∏–µ:'
    - '{task}'
  buttons:
    hurry_up: 'üì¢ –ü–æ—Ç–æ—Ä–æ–ø–∏—Ç—å'
    support: 'üíÅ –ü–æ–¥–¥–µ—Ä–∂–∫–∞'
